apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-secret
  annotations:
    argocd.argoproj.io/sync-wave: "201"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    template:
      type: Opaque
  data:
    - secretKey: CLOUDFLARE_API_KEY
      remoteRef:
        key: CLOUDFLARE_API_KEY
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: CLOUDFLARE_API_TOKEN
