apiVersion: networking.cfargotunnel.com/v1alpha1
kind: ClusterTunnel
metadata:
  name: lab
  annotations:
    argocd.argoproj.io/sync-wave: "209"
spec:
  newTunnel:
    name: hetzner-k0s-lab-tunnel # Name of your new tunnel on Cloudflare
  size: 2 # This is the number of replicas for cloudflared
  cloudflare:
    email: bazarjani.kian@gmail.com
    domain: bazza.dev
    secret: cloudflare-secret
    accountId: 1787e9f04a8eb611129f0945fa802ce8
