apiVersion: v1
kind: Pod
metadata:
  name: data-transfer-pod
spec:
  containers:
    - name: transfer-container
      image: ubuntu:20.04
      command: ["/bin/bash", "-c", "sleep infinity"]
      volumeMounts:
        - mountPath: /data
          name: data-volume
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: minecraft-data-pvc
