kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-data-pvc
  namespace: minecraft
spec:
  storageClassName: longhorn
  volumeName: pvc-068f462b-fa98-4108-8164-39a78c7e4d14
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
