apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: web-svc-binding
subjects:
  - kind: Service
    name: avelin-web-svc
    spec:
      fqdn: avelin.app
      protocol: http
      target: http://avelin-web-svc.avelin.svc.cluster.local
tunnelRef:
  kind: ClusterTunnel
  name: avelin
  disableDNSUpdates: false
