apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: sync-svc-binding
subjects:
  - kind: Service
    name: avelin-sync-svc
    spec:
      fqdn: sync.avelin.app
      protocol: http
      target: http://avelin-sync-svc.avelin.svc.cluster.local
tunnelRef:
  kind: ClusterTunnel
  name: avelin
  disableDNSUpdates: false
