apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: doppler-avelin
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-avelin-token
            key: dopplerToken
