apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secret
  annotations:
    argocd.argoproj.io/sync-wave: "201"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-avelin
    kind: SecretStore
  target:
    template:
      type: Opaque
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: DATABASE_URL
