apiVersion: batch/v1
kind: Job
metadata:
  name: avelin-db-migration
  namespace: avelin
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: avelin-migrate
          image: ghcr.io/avelinapp/migrate:v0.26.3
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DATABASE_URL
      restartPolicy: OnFailure
