apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-secret
  annotations:
    argocd.argoproj.io/sync-wave: "201"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-avelin
    kind: SecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: GITHUB_GHCR_SECRET
