apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth-secret
  annotations:
    argocd.argoproj.io/sync-wave: "201"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-avelin
    kind: SecretStore
  target:
    template:
      type: Opaque
  dataFrom:
    - find:
        path: GOOGLE_CLIENT_
