apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: doppler-cluster
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            namespace: external-secrets
            name: doppler-cluster-token
            key: dopplerToken
