apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn-gcp-backups
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    template:
      type: Opaque
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: LONGHORN_BACKUPS_GCS_ACCESS_KEY
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: LONGHORN_BACKUPS_GCS_SECRET
    - secretKey: AWS_ENDPOINTS
      remoteRef:
        key: LONGHORN_BACKUPS_GCS_ENDPOINT
